language: cpp
python:
  - "2.7"
matrix:
  include:
    - env: PLATFORM=osx BINDINGS_ARGS="platform=osx generate_bindings=true target=release" LIB_ARGS="platform=osx target=release wwise_sdk=../wwisesdk/2019.2.1.7250/"
      os: osx
      compiler: clang
      addons:
        homebrew:
          packages:
            - scons
            - p7zip
          update: false
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Homebrew
before_install:
  - wget https://gist.githubusercontent.com/alessandrofama/2f73d0fbb3f5b52605564a7ed823c2e8/raw/8b4487736c946b16d53cf059986f94c5ec9fe86c/ignoremd.sh
  - chmod +x ignoremd.sh
  - ./ignoremd.sh || travis_terminate 0
  - mkdir wwisesdk && cd wwisesdk
  - wget https://www.dropbox.com/s/z27mc0xls25mhlu/2019.2.1.7250.zip
  - if [[ "$PLATFORM" == "osx" ]]; then 7z x 2019.2.1.7250.zip; fi
  - cd ../
  - cd godot-cpp
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then scons $BINDINGS_ARGS && cd ../wwise-gdnative; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then scons $LIB_ARGS && cd ../waapiclient-gdnative; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then scons $LIB_ARGS; fi
script:
- echo "Build complete"