language: cpp
python:
  - "2.7"
matrix:
  include:
    - env: PLATFORM=osx LIB_ARGS="platform=osx target=release wwise_sdk=../wwisesdk/2019.2.1.7250/"
      os: osx
      compiler: clang
      addons:
        homebrew:
          packages:
            - scons
            - p7zip
          update: false
git:
  depth: false
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Homebrew
before_cache:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi
# Credit https://discourse.brew.sh/t/best-practice-for-homebrew-on-travis-brew-update-is-5min-to-build-time/5215/9
# Cache only .git files under "/usr/local/Homebrew" so "brew update" does not take 5min every build
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -delete; fi
before_install:
  - if [[ "$PLATFORM" == "osx" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install p7zip scons; fi
  - mkdir wwisesdk && cd wwisesdk
  - wget https://www.dropbox.com/s/xkbp73tz3ph39mj/2019.2.1.7250.zip
  - 7z x 2019.2.1.7250.zip
  - cd ../
  - cd godot-cpp
  - mkdir bin && cd bin
  - wget https://www.dropbox.com/s/hcwlmpjvns1f25p/headers.zip
  - 7z x headers.zip
  - cd ../include/gen/
  - wget https://www.dropbox.com/s/lw08yw81ge22del/gen.zip && 7z x gen.zip
  - cd ../../../wwise-gdnative
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then scons $LIB_ARGS && cd ../waapiclient-gdnative; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then scons $LIB_ARGS; fi
script:
- echo "Build complete"